cards/urls.py
from django.urls import path

from cards import views

app_name = 'cards'

urlpatterns = [
    path('', views.form_create, name='create-card'),
]

mtgcards/urls.py
from django.contrib import admin
from django.urls import path, include
from cards import views as card_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cards/', include('cards.urls')),
    path('', card_views.index, name='index')
]

cards/models.py
import uuid

from django.db import models

class Color(models.Model):
    RED = 'R'
    GREEN = 'G'
    BLUE = 'U'
    WHITE = 'W'
    BLACK = 'B'
    COLOR_CHOICES = [(RED, 'Red'), (GREEN, 'Green'), (BLUE, 'Blue'), (WHITE, 'White'), (BLACK, 'Black')]

    name = models.CharField(max_length=20)
    code = models.CharField(max_length=3, choices=COLOR_CHOICES)

    def __str__(self):
        return self.name

class Edition(models.Model):
    """
    These are constantly added to so we won't lock them into choice fields
    """
    name = models.CharField(max_length=100)
    code = models.CharField(max_length=3)

    def __str__(self):
        return f"{self.name}({self.code})"

    class Meta:
        ordering = ['name']


class Card(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100)
    mana_cost = models.CharField(max_length=100, null=True, blank=True)
    text = models.TextField(null=True, blank=True)
    flavor = models.TextField(null=True, blank=True)
    type = models.CharField(max_length=100)
    power = models.CharField(max_length=5)
    toughness = models.CharField(max_length=5)
    rarity = models.CharField(max_length=20)
    set_name = models.CharField(max_length=50)
    image_url = models.URLField(max_length=300)
    edition = models.ForeignKey(Edition, on_delete=models.CASCADE)
    colors = models.ManyToManyField(Color)

    @property
    def color_count(self):
        return self.colors.count()

    def __str__(self):
        return self.name

cards/forms.py
from django import forms

from cards.models import Card


class CardForm(forms.ModelForm):
    class Meta:
        model = Card
        exclude = ['id']

cards/views.py
import json

from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from cards.forms import CardForm
from cards.models import Card


def form_create(request):

    if request.method == 'POST':
        form = CardForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('https://www.google.com')

    else:
        form = CardForm()

    return render(request, 'cards/card_create.html', {'name': 'John', 'form': form})

def index(request):
    cards = Card.objects.order_by('?')[:9]

    return render(request, 'cards/index.html', {'cards': cards})

cards/templates/cards/card_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>MTG Top Picks</title>
</head>
<body>

<h1>Hello, {{ name }}</h1>
<form action="{% url 'cards:create-card' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Create">
</form>

</body>
</html>

cards/templates/cards/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Random MTG Cards{% endblock %}
{% block body %}
<div>
			<ul id="featured">
                {% for card in cards %}
                <li>
                    <a href="#"><img src="{{ card.image_url }}" alt="{{ card.name }}"></a>
					<h2>{{ card.name }}</h2>
					<h3>{{ card.edition }}</h3>
                </li>
                {% endfor %}
			</ul>
			<span>This website template has been designed by <a href="http://www.freewebsitetemplates.com/">Free Website Templates</a> for you, for free. You can replace all this text with your own text. You can remove any link to our website from this website template, you&#39;re free to use this website template without linking back to us. If you&#39;re having problems editing this website template, then don&#39;t hesitate to ask for help on the <a href="http://www.freewebsitetemplates.com/forums/">Forums</a>.</span>
</div>
{% endblock %}